UPDATE oxarticles SET OXTITLE_1=OXTITLE, OXVARNAME_1=OXVARNAME, OXVARSELECT_1=OXVARSELECT, OXSHORTDESC_1=OXSHORTDESC, OXSEARCHKEYS_1=OXSEARCHKEYS;
UPDATE oxattribute SET OXTITLE_1=OXTITLE;
UPDATE oxartextends SET OXLONGDESC_1=OXLONGDESC, OXTAGS_1=OXTAGS;
UPDATE oxcategories SET OXTITLE_1=OXTITLE, OXDESC_1=OXDESC, OXLONGDESC_1=OXLONGDESC, OXACTIVE_1=OXACTIVE;